/*cd \wamp64\bin\mysql\mysql5.7.31\bin*/
/*mysql -h localhost -u root*/

DROP DATABASE sqlix;


CREATE DATABASE sqlix DEFAULT CHARACTER 
SET utf8mb4;


USE sqlix;


CREATE TABLE QUALITE (
  NumQualite INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
  LibQuatile VARCHAR(30)
) ENGINE=INNODB;


CREATE TABLE PROVINCE(
  NumProvince INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
  NomProvince VARCHAR(30),
  NomGouverneur VARCHAR(30)
)ENGINE=INNODB;


CREATE TABLE VILLAGE(
  NumVillage INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  NomVillage VARCHAR(30),
  NbHuttes INT, 
  NumProvince INT,
  FOREIGN KEY (NumProvince) REFERENCES PROVINCE(NumProvince)
) ENGINE=INNODB;


CREATE TABLE HABITANT(
  NumHab INT PRIMARY KEY AUTO_INCREMENT,
  Nom VARCHAR(30),
  Age INT,
  NumQualite INT,
  NumVillage INT,
  FOREIGN KEY (NumQualite) REFERENCES QUALITE (NumQualite),
  FOREIGN KEY (NumVillage) REFERENCES VILLAGE(NumVillage)
) ENGINE=INNODB;


CREATE TABLE RESSERRE(
  NumResserre INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  NomResser VARCHAR(30),
  Superficie INT,
  NumVillage INT,
  FOREIGN KEY (NumVillage) REFERENCES VILLAGE(NumVillage)
) ENGINE=INNODB;


CREATE TABLE CATEGORIE(
  CodeCat CHAR(3) PRIMARY KEY NOT NULL,
  NomCateg VARCHAR(50) ,
  NbPoint INT 
) ENGINE=INNODB;


CREATE TABLE TROPHEE(
  NumTrophee INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  DatePrise DATETIME,
  CodeCat CHAR(3),
  NumPreneur INT,
  NumResserre INT,
  FOREIGN KEY (NumPreneur) REFERENCES HABITANT(NumHab),
  FOREIGN KEY (CodeCat) REFERENCES CATEGORIE(CodeCat),
  FOREIGN KEY (NumResserre) REFERENCES RESSERRE(NumResserre)
) ENGINE=INNODB;


CREATE TABLE POTION(
  NumPotion INT NOT NULL AUTO_INCREMENT, 
  Libpotion VARCHAR(40),
  Formule VARCHAR(30),
  ConstituantPrincipal VARCHAR(30),
  PRIMARY KEY (NumPotion)
) ENGINE=INNODB;


CREATE TABLE FABRIQUER(
  NumPotion INT NOT NULL,
  NumHab INT,
  PRIMARY KEY (NumPotion, NumHab),
  FOREIGN KEY (NumPotion) REFERENCES POTION(NumPotion),
  FOREIGN KEY (NumHab) REFERENCES HABITANT(NumHab)
) ENGINE=INNODB;


CREATE TABLE ABSORBER(
  NumPotion INT NOT NULL,
  DateA DATETIME,
  NumHab INT,
  Quatite INT,
  PRIMARY KEY (NumPotion, DateA, NumHab),
  FOREIGN KEY(NumPotion) REFERENCES POTION(NumPotion),
  FOREIGN KEY(NumHab) REFERENCES HABITANT(NumHab)
) ENGINE=INNODB;



